'use client'
import { useState, useEffect, useRef } from 'react'
import { FileText, Share2, Download, Phone, AlertTriangle, Heart, Shield, Plus, X, Droplets, PawPrint } from 'lucide-react'
import { createClient } from '@/lib/supabase'

const MOBILITY_OPTIONS = ['Mobile Adult', 'Elderly', 'Elderly (needs driver)', 'Disabled', 'Wheelchair', 'No Vehicle', 'Medical Equipment', 'Other']

export default function EmergencyCardPage() {
  const cardRef = useRef<HTMLDivElement>(null)
  const [saved, setSaved] = useState(false)
  const supabase = createClient()

  const [profile, setProfile] = useState({
    name: '',
    address: '',
    phone: '',
    bloodType: '',
    allergies: '',
    emergencyContacts: [{ name: '', phone: '', relationship: '' }] as { name: string; phone: string; relationship: string }[],
    mobility: 'Mobile Adult',
    mobilityOther: '',
    medications: '',
    medicalEquipment: '',
    pets: '',
    languages: '',
    evacuationRoute: '',
    destinationAddress: '',
  })

  useEffect(() => {
    async function load() {
      // Priority 1: previously saved emergency card data
      try {
        const raw = localStorage.getItem('wfa_emergency_card')
        if (raw) {
          const p = JSON.parse(raw)
          if (p.name || p.phone || p.address) {
            setProfile(prev => ({ ...prev, ...p }))
            return
          }
        }
      } catch {}

      // Priority 2: Supabase profile
      try {
        const { data: { user } } = await supabase.auth.getUser()
        if (user) {
          const { data: p } = await supabase.from('profiles').select('*').eq('id', user.id).single()
          if (p) {
            setProfile(prev => ({
              ...prev,
              name: p.full_name || '',
              address: p.address || '',
              phone: p.phone || '',
              languages: p.household_languages || '',
              emergencyContacts: p.emergency_contact_name
                ? [{ name: p.emergency_contact_name, phone: p.emergency_contact_phone || '', relationship: '' }]
                : prev.emergencyContacts,
            }))
          }
        }
      } catch {}
    }
    load()
  }, [])

  function update<K extends keyof typeof profile>(key: K, value: typeof profile[K]) {
    setProfile(p => {
      const next = { ...p, [key]: value }
      try { localStorage.setItem('wfa_emergency_card', JSON.stringify(next)) } catch {}
      return next
    })
    setSaved(false)
  }

  function saveNow() {
    try { localStorage.setItem('wfa_emergency_card', JSON.stringify(profile)) } catch {}
    setSaved(true)
    setTimeout(() => setSaved(false), 2000)
  }

  function addContact() {
    update('emergencyContacts', [...profile.emergencyContacts, { name: '', phone: '', relationship: '' }])
  }

  function removeContact(i: number) {
    update('emergencyContacts', profile.emergencyContacts.filter((_, idx) => idx !== i))
  }

  function updateContact(i: number, field: 'name' | 'phone' | 'relationship', value: string) {
    const next = profile.emergencyContacts.map((c, idx) => idx === i ? { ...c, [field]: value } : c)
    update('emergencyContacts', next)
  }

  function shareCard() {
    const text = buildShareText()
    if (navigator.share) {
      navigator.share({ title: 'My Wildfire Emergency Card', text }).catch(() => {})
    } else {
      navigator.clipboard?.writeText(text).then(() => alert('Card copied to clipboard. Paste it in any app or message to share.'))
    }
  }

  function buildShareText() {
    const mobilityLabel = profile.mobility === 'Other' && profile.mobilityOther ? profile.mobilityOther : profile.mobility
    const lines = [
      '🔥 WILDFIRE EMERGENCY CARD — Minutes Matter',
      `Name: ${profile.name || 'Unknown'}`,
      `Phone: ${profile.phone || 'Unknown'}`,
      `Address: ${profile.address || 'Unknown'}`,
      profile.bloodType ? `Blood Type: ${profile.bloodType}` : '',
      profile.allergies ? `⚠ Allergies: ${profile.allergies}` : '',
      '',
      '— Emergency Contacts —',
      ...profile.emergencyContacts.filter(c => c.name).map(c => `${c.name}${c.relationship ? ` (${c.relationship})` : ''}: ${c.phone}`),
      '',
      profile.mobility !== 'Mobile Adult' ? `Mobility: ${mobilityLabel}` : '',
      profile.medications ? `Medications: ${profile.medications}` : '',
      profile.medicalEquipment ? `Medical Equipment: ${profile.medicalEquipment}` : '',
      profile.pets ? `Pets: ${profile.pets}` : '',
      profile.languages ? `Languages: ${profile.languages}` : '',
      '',
      profile.evacuationRoute ? `Evacuation Route: ${profile.evacuationRoute}` : '',
      profile.destinationAddress ? `Going to: ${profile.destinationAddress}` : '',
      '',
      '— Emergency Numbers —',
      '911 · FEMA: 1-800-621-3362 · Red Cross: 1-800-733-2767',
      '',
      'Generated by minutesmatter.app',
    ].filter(l => l !== null && l !== undefined)
    return lines.filter(l => l !== '').join('\n')
  }

  const mobilityLabel = profile.mobility === 'Other' && profile.mobilityOther ? profile.mobilityOther : profile.mobility
  const hasCriticalNeeds = profile.medications || profile.medicalEquipment || (profile.mobility !== 'Mobile Adult')

  return (
    <div className="p-6 max-w-2xl mx-auto">
      {/* Header */}
      <div className="mb-6">
        <div className="flex items-center gap-2 text-forest-600 text-sm font-medium mb-3">
          <FileText className="w-4 h-4" />
          CAREGIVER · EMERGENCY CARD
        </div>
        <h1 className="font-display text-3xl font-bold text-gray-900 mb-1">My Emergency Card</h1>
        <p className="text-gray-500 text-sm mb-4">
          Your personal card for first responders and shelter staff. Fills in what 911 can&apos;t know — your meds, your pets, your route.
          <strong className="text-gray-700"> Auto-saved to your device.</strong>
        </p>
        <div className="flex gap-3 flex-wrap">
          <button onClick={shareCard}
            className="flex items-center gap-2 px-5 py-2.5 bg-forest-600 hover:bg-forest-700 rounded-xl text-white font-semibold transition-colors">
            <Share2 className="w-4 h-4" />
            Share / AirDrop
          </button>
          <button onClick={() => window.print()}
            className="flex items-center gap-2 px-5 py-2.5 bg-white border border-gray-200 hover:bg-gray-50 rounded-xl text-gray-700 font-semibold transition-colors">
            <Download className="w-4 h-4" />
            Save as PDF
          </button>
          {saved && <span className="text-signal-safe text-sm font-medium self-center">✓ Saved</span>}
        </div>
        <p className="text-gray-400 text-xs mt-3">
          On iPhone: tap <strong>Share / AirDrop</strong> → &quot;AirDrop&quot; to send to another device, or &quot;Add to Notes&quot; to save offline.
        </p>
      </div>

      {/* Edit form */}
      <div className="space-y-4 no-print mb-8">
        {/* Identity */}
        <div className="card p-5">
          <h2 className="text-gray-700 font-semibold text-sm mb-3 flex items-center gap-2">
            <Heart className="w-4 h-4 text-signal-danger" /> Personal Info
          </h2>
          <div className="grid sm:grid-cols-2 gap-3">
            <div>
              <label className="text-gray-500 text-xs block mb-1">Full name</label>
              <input type="text" value={profile.name} onChange={e => update('name', e.target.value)}
                placeholder="Jane Doe" className="input" />
            </div>
            <div>
              <label className="text-gray-500 text-xs block mb-1">Phone</label>
              <input type="tel" value={profile.phone} onChange={e => update('phone', e.target.value)}
                placeholder="+1 (555) 000-0000" className="input" />
            </div>
            <div className="sm:col-span-2">
              <label className="text-gray-500 text-xs block mb-1">Home address</label>
              <input type="text" value={profile.address} onChange={e => update('address', e.target.value)}
                placeholder="123 Main St, City, CA 95003" className="input" />
            </div>
            <div>
              <label className="text-gray-500 text-xs block mb-1">Blood type <span className="text-gray-400">(optional)</span></label>
              <select value={profile.bloodType} onChange={e => update('bloodType', e.target.value)} className="input">
                <option value="">Unknown</option>
                {['A+','A-','B+','B-','AB+','AB-','O+','O-'].map(t => <option key={t}>{t}</option>)}
              </select>
            </div>
            <div>
              <label className="text-gray-500 text-xs block mb-1">Languages (non-English)</label>
              <input type="text" value={profile.languages} onChange={e => update('languages', e.target.value)}
                placeholder="e.g. Spanish, Cantonese" className="input" />
            </div>
            <div className="sm:col-span-2">
              <label className="text-gray-500 text-xs block mb-1">Allergies / reactions <span className="text-gray-400">(critical for shelters)</span></label>
              <input type="text" value={profile.allergies} onChange={e => update('allergies', e.target.value)}
                placeholder="e.g. penicillin (anaphylaxis), latex, shellfish" className="input" />
            </div>
          </div>
        </div>

        {/* Medical needs */}
        <div className="card p-5">
          <h2 className="text-gray-700 font-semibold text-sm mb-3 flex items-center gap-2">
            <Droplets className="w-4 h-4 text-signal-info" /> Medical Needs
            {hasCriticalNeeds && <span className="text-xs bg-signal-danger/10 text-signal-danger border border-signal-danger/30 px-2 py-0.5 rounded-full font-normal">Has critical needs</span>}
          </h2>
          <div className="space-y-3">
            <div>
              <label className="text-gray-500 text-xs block mb-1">Mobility level</label>
              <select
                value={profile.mobility.startsWith('Other') ? 'Other' : profile.mobility}
                onChange={e => update('mobility', e.target.value)}
                className="input"
              >
                {MOBILITY_OPTIONS.map(m => <option key={m} value={m}>{m}</option>)}
              </select>
              {profile.mobility === 'Other' && (
                <input type="text" value={profile.mobilityOther} onChange={e => update('mobilityOther', e.target.value)}
                  placeholder="Describe your situation…" className="input mt-2" autoFocus />
              )}
            </div>
            <div>
              <label className="text-gray-500 text-xs block mb-1">Medications <span className="text-gray-400">— responders need this to help you at a shelter</span></label>
              <textarea value={profile.medications} onChange={e => update('medications', e.target.value)}
                placeholder="e.g. Metformin 500mg twice daily, Lisinopril 10mg, insulin (refrigerated), blood thinners"
                rows={2} className="input resize-none" />
            </div>
            <div>
              <label className="text-gray-500 text-xs block mb-1">Medical equipment / power needs</label>
              <input type="text" value={profile.medicalEquipment} onChange={e => update('medicalEquipment', e.target.value)}
                placeholder="e.g. O2 concentrator (needs outlet), CPAP, nebulizer, insulin pump" className="input" />
            </div>
          </div>
        </div>

        {/* Emergency contacts */}
        <div className="card p-5">
          <div className="flex items-center justify-between mb-3">
            <h2 className="text-gray-700 font-semibold text-sm flex items-center gap-2">
              <Phone className="w-4 h-4 text-forest-600" /> Emergency Contacts
            </h2>
            <button onClick={addContact} className="flex items-center gap-1 text-xs text-forest-600 hover:text-forest-700 font-medium">
              <Plus className="w-3 h-3" /> Add
            </button>
          </div>
          <div className="space-y-3">
            {profile.emergencyContacts.map((c, i) => (
              <div key={i} className="flex gap-2 items-start">
                <div className="flex-1 grid sm:grid-cols-3 gap-2">
                  <input type="text" value={c.name} onChange={e => updateContact(i, 'name', e.target.value)}
                    placeholder="Name" className="input" />
                  <input type="tel" value={c.phone} onChange={e => updateContact(i, 'phone', e.target.value)}
                    placeholder="Phone" className="input font-mono" />
                  <input type="text" value={c.relationship} onChange={e => updateContact(i, 'relationship', e.target.value)}
                    placeholder="Relationship (e.g. spouse)" className="input" />
                </div>
                {profile.emergencyContacts.length > 1 && (
                  <button onClick={() => removeContact(i)} className="mt-2.5 text-gray-400 hover:text-signal-danger transition-colors">
                    <X className="w-4 h-4" />
                  </button>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Pets & evacuation */}
        <div className="card p-5">
          <h2 className="text-gray-700 font-semibold text-sm mb-3 flex items-center gap-2">
            <PawPrint className="w-4 h-4 text-amber-500" /> Pets & Evacuation Plan
          </h2>
          <div className="space-y-3">
            <div>
              <label className="text-gray-500 text-xs block mb-1">Pets <span className="text-gray-400">(shelters need this to direct you to pet-friendly locations)</span></label>
              <input type="text" value={profile.pets} onChange={e => update('pets', e.target.value)}
                placeholder="e.g. Bella (lab), 2 cats, fish tank (can't take)" className="input" />
            </div>
            <div>
              <label className="text-gray-500 text-xs block mb-1">Primary evacuation route</label>
              <input type="text" value={profile.evacuationRoute} onChange={e => update('evacuationRoute', e.target.value)}
                placeholder="e.g. Hwy 1 North → I-5 North" className="input" />
            </div>
            <div>
              <label className="text-gray-500 text-xs block mb-1">Destination / meeting point</label>
              <input type="text" value={profile.destinationAddress} onChange={e => update('destinationAddress', e.target.value)}
                placeholder="e.g. Sister's house: 456 Oak Ave, Sacramento" className="input" />
            </div>
          </div>
        </div>
      </div>

      {/* Printable / shareable card */}
      <div ref={cardRef} id="emergency-card" className="print-card rounded-xl border-2 border-gray-300 bg-white overflow-hidden">
        {/* Header */}
        <div className="bg-red-50 border-b-2 border-red-200 px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-red-100 border border-red-200 flex items-center justify-center">
              <Shield className="w-5 h-5 text-red-600" />
            </div>
            <div>
              <div className="font-bold text-gray-900 text-base uppercase tracking-wide">Wildfire Emergency Card</div>
              <div className="text-red-600/70 text-xs">minutesmatter.app · Show this to any shelter or responder</div>
            </div>
          </div>
          <div className="text-right text-xs text-gray-400">
            <div>Updated</div>
            <div className="font-mono">{new Date().toLocaleDateString()}</div>
          </div>
        </div>

        <div className="p-5 space-y-4">
          {/* Identity row */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <div className="text-gray-400 text-xs uppercase tracking-wider mb-0.5">Name</div>
              <div className="text-gray-900 font-bold text-lg">{profile.name || '______________________'}</div>
            </div>
            <div>
              <div className="text-gray-400 text-xs uppercase tracking-wider mb-0.5">Phone</div>
              <div className="text-gray-900 font-bold text-lg font-mono">{profile.phone || '______________________'}</div>
            </div>
            <div className="col-span-2">
              <div className="text-gray-400 text-xs uppercase tracking-wider mb-0.5">Home Address</div>
              <div className="text-gray-900 font-semibold">{profile.address || '______________________________________'}</div>
            </div>
            {(profile.bloodType || profile.languages || profile.allergies) && (
              <div className="col-span-2 flex flex-wrap gap-2">
                {profile.bloodType && (
                  <span className="bg-red-50 border border-red-200 text-red-700 text-xs font-bold px-2 py-1 rounded-lg">
                    Blood: {profile.bloodType}
                  </span>
                )}
                {profile.languages && (
                  <span className="bg-blue-50 border border-blue-200 text-blue-700 text-xs font-medium px-2 py-1 rounded-lg">
                    Speaks: {profile.languages}
                  </span>
                )}
                {profile.allergies && (
                  <span className="bg-signal-warn/10 border border-signal-warn/40 text-signal-warn text-xs font-bold px-2 py-1 rounded-lg">
                    ⚠ ALLERGY: {profile.allergies}
                  </span>
                )}
              </div>
            )}
          </div>

          {/* Critical needs banner */}
          {hasCriticalNeeds && (
            <div className="bg-signal-danger/10 border-2 border-signal-danger/40 rounded-lg p-3">
              <div className="text-signal-danger font-bold text-xs uppercase tracking-wider mb-1.5 flex items-center gap-1">
                <AlertTriangle className="w-3.5 h-3.5" /> Critical Needs — Read Before Placing
              </div>
              <div className="space-y-1 text-sm">
                {profile.mobility !== 'Mobile Adult' && (
                  <div><span className="font-semibold text-gray-700">Mobility:</span> <span className="text-gray-600">{mobilityLabel}</span></div>
                )}
                {profile.medications && (
                  <div><span className="font-semibold text-gray-700">Medications:</span> <span className="text-gray-600">{profile.medications}</span></div>
                )}
                {profile.medicalEquipment && (
                  <div><span className="font-semibold text-gray-700">Equipment:</span> <span className="text-gray-600 font-medium">{profile.medicalEquipment}</span></div>
                )}
              </div>
            </div>
          )}

          <div className="border-t border-gray-100" />

          {/* Emergency contacts */}
          <div>
            <div className="text-gray-400 text-xs uppercase tracking-wider mb-2">Emergency Contacts</div>
            <div className="grid grid-cols-1 gap-1.5">
              {profile.emergencyContacts.filter(c => c.name || c.phone).length > 0
                ? profile.emergencyContacts.filter(c => c.name || c.phone).map((c, i) => (
                    <div key={i} className="flex items-center gap-2 bg-gray-50 border border-gray-100 rounded-lg px-3 py-2">
                      <Phone className="w-3 h-3 text-gray-400 shrink-0" />
                      <span className="text-gray-900 font-semibold text-sm">{c.name}</span>
                      {c.relationship && <span className="text-gray-400 text-xs">({c.relationship})</span>}
                      <span className="ml-auto text-gray-900 font-mono text-sm">{c.phone}</span>
                    </div>
                  ))
                : <div className="text-gray-400 text-sm">No contacts added yet</div>
              }
            </div>
          </div>

          <div className="border-t border-gray-100" />

          {/* Pets / route */}
          {(profile.pets || profile.evacuationRoute || profile.destinationAddress) && (
            <div className="grid grid-cols-1 gap-2 text-sm">
              {profile.pets && (
                <div><span className="font-semibold text-gray-700">Pets:</span> <span className="text-gray-600">{profile.pets}</span></div>
              )}
              {profile.evacuationRoute && (
                <div><span className="font-semibold text-gray-700">Route:</span> <span className="text-gray-600">{profile.evacuationRoute}</span></div>
              )}
              {profile.destinationAddress && (
                <div><span className="font-semibold text-gray-700">Going to:</span> <span className="text-gray-600">{profile.destinationAddress}</span></div>
              )}
            </div>
          )}

          {(profile.pets || profile.evacuationRoute || profile.destinationAddress) && <div className="border-t border-gray-100" />}

          {/* Emergency numbers */}
          <div className="grid grid-cols-2 gap-2 text-xs">
            <div className="flex justify-between bg-gray-50 border border-gray-100 rounded-lg px-3 py-2">
              <span className="text-gray-500">Emergency</span>
              <span className="text-gray-900 font-mono font-bold">911</span>
            </div>
            <div className="flex justify-between bg-gray-50 border border-gray-100 rounded-lg px-3 py-2">
              <span className="text-gray-500">FEMA Helpline</span>
              <span className="text-gray-900 font-mono font-bold">1-800-621-3362</span>
            </div>
            <div className="flex justify-between bg-gray-50 border border-gray-100 rounded-lg px-3 py-2">
              <span className="text-gray-500">Red Cross</span>
              <span className="text-gray-900 font-mono font-bold">1-800-733-2767</span>
            </div>
            <div className="flex justify-between bg-gray-50 border border-gray-100 rounded-lg px-3 py-2">
              <span className="text-gray-500">Crisis Text</span>
              <span className="text-gray-900 font-mono font-bold">Text HOME→741741</span>
            </div>
          </div>

          <div className="border-t border-gray-100 pt-2 text-gray-300 text-xs text-center">
            Minutes Matter Emergency Card · minutesmatter.app · Auto-saved to your device
          </div>
        </div>
      </div>

      <style jsx global>{`
        @media print {
          .no-print { display: none !important; }
          body { background: white !important; }
          .print-card { border-color: #999 !important; }
        }
      `}</style>
    </div>
  )
}
