import { NextResponse, NextRequest } from 'next/server'
import { checkRateLimit, getClientIp } from '@/lib/ratelimit'
import { validateString, ValidationError } from '@/lib/validate'

/** Token ping check-in: home evacuation statuses only (matches HomeEvacuationStatus). */
const VALID_STATUSES = ['not_evacuated', 'evacuated', 'cannot_evacuate']
// UUID v4 pattern — tokens are generated by the app
const TOKEN_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

async function trySupabaseUpsert(token: string, status: string, confirmed_at: string) {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  if (!url || !key) return

  try {
    const { createClient } = await import('@supabase/supabase-js')
    const supabase = createClient(url, key)
    await supabase
      .from('checkin_events')
      .upsert({ token, status, confirmed_at }, { onConflict: 'token' })
  } catch {
    // Supabase unavailable or table doesn't exist — BroadcastChannel handles real-time
  }
}

export async function POST(request: NextRequest) {
  // Rate limit: 10 check-ins per minute per IP
  const ip = getClientIp(request)
  if (!checkRateLimit(ip, 'checkin', 10, 60_000)) {
    return NextResponse.json({ error: 'Too many requests' }, { status: 429 })
  }

  try {
    const body = await request.json()

    const token = validateString(body.token, 'token', {
      maxLength: 36,
      minLength: 36,
      pattern: TOKEN_PATTERN,
    })
    const status = validateString(body.status, 'status', {
      allowedValues: VALID_STATUSES,
    })
    const confirmed_at = body.confirmed_at
      ? validateString(body.confirmed_at, 'confirmed_at', { maxLength: 30 })
      : new Date().toISOString()

    trySupabaseUpsert(token, status, confirmed_at).catch(() => {})

    return NextResponse.json({ success: true, status, confirmed_at })
  } catch (err) {
    if (err instanceof ValidationError) {
      return NextResponse.json({ error: err.message }, { status: 400 })
    }
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 })
  }
}
