export type FacilityType = 'nuclear' | 'chemical' | 'lng_energy'

export interface HazardFacility {
  id: string
  name: string
  type: FacilityType
  lat: number
  lng: number
  county: string
  state: string
  riskNote: string
}

export const HAZARD_FACILITIES: HazardFacility[] = [
  // ── Nuclear ──────────────────────────────────────────────────────────────
  {
    id: 'nuc-01',
    name: 'Duke Energy — McGuire Nuclear Station',
    type: 'nuclear',
    lat: 35.4325, lng: -80.9478,
    county: 'Mecklenburg', state: 'NC',
    riskNote: 'Nuclear plant with a 10-mile emergency planning zone. In a wildfire scenario, smoke, road closures, and access disruption are primary concerns for nearby residents.',
  },
  {
    id: 'nuc-02',
    name: 'Duke Energy — Catawba Nuclear Station',
    type: 'nuclear',
    lat: 35.0522, lng: -81.0711,
    county: 'York', state: 'SC',
    riskNote: 'Two-unit nuclear plant on Lake Wylie. Serves as a regional power hub — disruption affects the Carolinas grid. 10-mile EPZ covers parts of NC and SC.',
  },
  {
    id: 'nuc-03',
    name: 'Duke Energy — Oconee Nuclear Station',
    type: 'nuclear',
    lat: 34.7919, lng: -82.8997,
    county: 'Oconee', state: 'SC',
    riskNote: 'Largest nuclear plant in the Southeast by capacity. 10-mile emergency planning zone includes parts of Oconee and Pickens counties.',
  },
  {
    id: 'nuc-04',
    name: 'Brunswick Nuclear Plant',
    type: 'nuclear',
    lat: 33.9587, lng: -78.0222,
    county: 'Brunswick', state: 'NC',
    riskNote: 'Coastal nuclear plant. Wildfire and hurricane risk overlap. 10-mile EPZ covers parts of Brunswick and Columbus counties.',
  },
  {
    id: 'nuc-05',
    name: 'Shearon Harris Nuclear Plant',
    type: 'nuclear',
    lat: 35.6325, lng: -78.9561,
    county: 'Wake', state: 'NC',
    riskNote: 'Single-unit plant southwest of Raleigh. 10-mile EPZ covers rural Wake, Chatham, and Harnett counties — areas at elevated wildfire risk.',
  },
  {
    id: 'nuc-06',
    name: 'Vogtle Electric Generating Plant',
    type: 'nuclear',
    lat: 33.1419, lng: -81.7625,
    county: 'Burke', state: 'GA',
    riskNote: 'Recently expanded to 4 units. 10-mile EPZ covers Burke and surrounding counties in eastern Georgia.',
  },
  {
    id: 'nuc-07',
    name: 'Sequoyah Nuclear Plant',
    type: 'nuclear',
    lat: 35.2261, lng: -85.0872,
    county: 'Hamilton', state: 'TN',
    riskNote: 'TVA-operated plant on Chickamauga Lake. 10-mile EPZ includes parts of Hamilton and Bradley counties in Tennessee.',
  },
  {
    id: 'nuc-08',
    name: 'Watts Bar Nuclear Plant',
    type: 'nuclear',
    lat: 35.6047, lng: -84.7875,
    county: 'Rhea', state: 'TN',
    riskNote: 'TVA facility on the Tennessee River. Surrounding Rhea and Meigs counties have elevated wildfire risk in drought conditions.',
  },
  {
    id: 'nuc-09',
    name: 'Surry Power Station',
    type: 'nuclear',
    lat: 37.1653, lng: -76.6983,
    county: 'Surry', state: 'VA',
    riskNote: 'Dominion Energy plant on the James River. 10-mile EPZ covers rural Surry County — limited evacuation route capacity.',
  },
  {
    id: 'nuc-10',
    name: 'North Anna Power Station',
    type: 'nuclear',
    lat: 38.0639, lng: -77.7911,
    county: 'Louisa', state: 'VA',
    riskNote: 'Two-unit plant near Lake Anna. 10-mile EPZ spans Louisa, Spotsylvania, and Orange counties — rural roads are primary evacuation routes.',
  },

  // ── Chemical / Petrochemical ───────────────────────────────────────────
  {
    id: 'chem-01',
    name: 'Chemours — Fayetteville Works',
    type: 'chemical',
    lat: 34.9996, lng: -78.8958,
    county: 'Cumberland', state: 'NC',
    riskNote: 'Chemical manufacturing facility. Produces fluorochemicals. Fire near this site may release toxic smoke. Shelter-in-place protocols may be triggered.',
  },
  {
    id: 'chem-02',
    name: 'Nucor Steel — Charlotte',
    type: 'chemical',
    lat: 35.4064, lng: -80.8494,
    county: 'Mecklenburg', state: 'NC',
    riskNote: 'Electric arc furnace steel plant. Large fuel and chemical storage on-site. Fire risk includes stored oils and industrial gases.',
  },
  {
    id: 'chem-03',
    name: 'Colonial Pipeline — Shelby Terminal',
    type: 'chemical',
    lat: 35.3028, lng: -81.5462,
    county: 'Cleveland', state: 'NC',
    riskNote: 'Major petroleum pipeline terminal. Wildfire near fuel storage tanks creates extreme explosion and toxic smoke risk. Large evacuation zone may be needed.',
  },
  {
    id: 'chem-04',
    name: 'Bayer CropScience — Institute Plant',
    type: 'chemical',
    lat: 38.4207, lng: -81.8326,
    county: 'Kanawha', state: 'WV',
    riskNote: 'Site of a 1985 methyl isocyanate release (same chemical as Bhopal). Chemical fire here could require large-scale evacuation of the Kanawha Valley.',
  },
  {
    id: 'chem-05',
    name: 'DuPont — Richmond Works',
    type: 'chemical',
    lat: 37.5078, lng: -77.4914,
    county: 'Henrico', state: 'VA',
    riskNote: 'Large chemical manufacturing campus near Richmond. Multiple hazardous materials stored on-site. Fire could release toxic compounds.',
  },
  {
    id: 'chem-06',
    name: 'Eastman Chemical — Kingsport',
    type: 'chemical',
    lat: 36.5184, lng: -82.5618,
    county: 'Sullivan', state: 'TN',
    riskNote: 'One of the largest chemical plants in the US. Produces acetyl chemicals and plastics. Fire could release acetic acid and other hazardous vapors.',
  },
  {
    id: 'chem-07',
    name: 'BASF — Freeport Complex',
    type: 'chemical',
    lat: 28.9572, lng: -95.3597,
    county: 'Brazoria', state: 'TX',
    riskNote: 'Major petrochemical complex on the Gulf Coast. Produces a wide range of industrial chemicals. Fire risk is elevated during dry Gulf Coast conditions.',
  },
  {
    id: 'chem-08',
    name: 'ExxonMobil — Baytown Refinery',
    type: 'chemical',
    lat: 29.7602, lng: -95.0147,
    county: 'Harris', state: 'TX',
    riskNote: 'Largest refinery in the US. A fire could trigger massive explosions and release of benzene, hydrogen sulfide, and other toxic chemicals. Multi-mile exclusion zone possible.',
  },
  {
    id: 'chem-09',
    name: 'GreenField Environmental — Columbia',
    type: 'chemical',
    lat: 33.9987, lng: -81.1195,
    county: 'Richland', state: 'SC',
    riskNote: 'Hazardous waste treatment and disposal facility. Fire here could release mixed industrial toxins. Nearby residents should follow shelter-in-place guidance.',
  },
  {
    id: 'chem-10',
    name: 'Arkema — Crosby Plant',
    type: 'chemical',
    lat: 29.9163, lng: -95.0581,
    county: 'Harris', state: 'TX',
    riskNote: 'Organic peroxide manufacturer. This site exploded during Hurricane Harvey (2017) when refrigeration failed. Fire/heat can trigger spontaneous explosion of stored chemicals.',
  },

  // ── LNG / Energy ──────────────────────────────────────────────────────
  {
    id: 'lng-01',
    name: 'Dominion Energy — Cove Point LNG',
    type: 'lng_energy',
    lat: 38.4072, lng: -76.3932,
    county: 'Calvert', state: 'MD',
    riskNote: 'Major LNG export terminal on the Chesapeake Bay. LNG fires burn extremely hot and resist conventional suppression. Large exclusion zone required.',
  },
  {
    id: 'lng-02',
    name: 'Piedmont Natural Gas — Charlotte',
    type: 'lng_energy',
    lat: 35.2271, lng: -80.8431,
    county: 'Mecklenburg', state: 'NC',
    riskNote: 'Urban natural gas storage and distribution hub. Fire or rupture could disrupt gas supply to much of the Charlotte region.',
  },
  {
    id: 'lng-03',
    name: 'Duke Energy — Marshall Steam Station',
    type: 'lng_energy',
    lat: 35.5422, lng: -80.9319,
    county: 'Iredell', state: 'NC',
    riskNote: 'Coal ash impoundments on Lake Norman. Wildfire in the area can compromise containment structures and risk environmental contamination of the lake.',
  },
  {
    id: 'lng-04',
    name: 'Progress Energy — Mayo Plant',
    type: 'lng_energy',
    lat: 36.5041, lng: -79.0428,
    county: 'Person', state: 'NC',
    riskNote: 'Coal-fired plant with large fuel storage. Wildfire risk in surrounding Person County is elevated during drought conditions.',
  },
  {
    id: 'lng-05',
    name: 'Spectra Energy — Pine Needle LNG',
    type: 'lng_energy',
    lat: 36.0122, lng: -79.8911,
    county: 'Guilford', state: 'NC',
    riskNote: 'Underground LNG storage facility. Provides peak-day natural gas supply for the Piedmont Triad region. Disruption affects millions of customers.',
  },
  {
    id: 'lng-06',
    name: 'TC Energy — Buckingham Compressor Station',
    type: 'lng_energy',
    lat: 37.5526, lng: -78.6944,
    county: 'Buckingham', state: 'VA',
    riskNote: 'Transcontinental Gas Pipe Line compressor station. Serves as a key node in the eastern US natural gas network. Fire or damage affects regional energy supply.',
  },
  {
    id: 'lng-07',
    name: 'Sabine Pass LNG Terminal',
    type: 'lng_energy',
    lat: 29.7269, lng: -93.8978,
    county: 'Cameron', state: 'LA',
    riskNote: "Largest LNG export facility in the US. LNG pool fires can reach 1,800°F and are nearly impossible to extinguish — they must burn out. Exclusion zone is measured in miles.",
  },
  {
    id: 'lng-08',
    name: 'Freeport LNG Terminal',
    type: 'lng_energy',
    lat: 28.8564, lng: -95.3597,
    county: 'Brazoria', state: 'TX',
    riskNote: 'Major LNG export terminal on Quintana Island. Explosion in 2022 caused 3-month shutdown. Fire risk is high in dry coastal conditions.',
  },
  {
    id: 'lng-09',
    name: 'Dominion Energy — Surry Substation',
    type: 'lng_energy',
    lat: 37.1683, lng: -76.7007,
    county: 'Surry', state: 'VA',
    riskNote: 'High-voltage transmission substation adjacent to Surry Nuclear Plant. Wildfire damage could knock out power to the nuclear facility and surrounding region.',
  },
  {
    id: 'lng-10',
    name: 'Southern Company — Plant Vogtle Energy Complex',
    type: 'lng_energy',
    lat: 33.1450, lng: -81.7600,
    county: 'Burke', state: 'GA',
    riskNote: 'Combined nuclear and gas generating complex. One of the most significant power generation sites in the Southeast — serves millions of Georgia customers.',
  },
]
